apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mods-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: mods-api
    spec:
      containers:
      - image: modsapiacr.azurecr.io/mods-api
        name: mods-api
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mods-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    run: mods-api
